trigger:
- main  # Runs the pipeline when code is pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses the latest Ubuntu VM

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Change based on your project needs

- script: |
    dotnet restore
    dotnet build --configuration Release
  displayName: 'Restore and Build'

- script: |
    dotnet test --configuration Release
  displayName: 'Run Unit Tests'

# **NEW: Publish the build output**
- script: |
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Application'

# **NEW: Store the artifact for deployment**
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
